config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  match '/users',   to: 'users#index',   via: 'get'
  resources :banks
  resources :companies
  resources :suppliers
  resources :budgetlines
  resources :backups
  resources :home
  resources :bulk_upload
  resources :profiles
  resources :users do
    member do
      get 'details'
      get :edit_password
      put :update_password  
      delete :destroy
    end
  end
  get 'unauthorized', to: 'errors#unauthorized', as: :unauthorized

  resources :budgets do
    member do
      get 'details'
    end
  end
  resources :checks do
    member do
      get 'details'
    end
  end
  resources :details
  resources :searchs
  get '/checks/authorize/:id', to: 'checks#authorize', as: 'authorize_check'
  get '/checks/deauthorize/:id', to: 'checks#deauthorize', as: 'deauthorize_check'
  get 'budgets/:id/export', to: 'budgets#export', as: 'export_budget'
  get '/', to: redirect('home/index')
  resource :example, constraints: -> { Rails.env.development? }
  post 'bulkupload', to: 'bulk_upload#create', as: :bulkupload
  get 'bulkupload/download_layout', to: 'bulk_upload#download_layout', as: :download_layout
end

app/models/budget.rb
class Budget
  include HTTParty
  base_uri Rails.application.config.base_api
  include ActiveModel::Model

  attr_accessor :cve_presupuesto, :anio_presupuesto, :nombre_presupuesto, :monto_presupuestado, 
                :monto_erogado, :monto_por_erogar, :IdInterno, :empresa_fk

  def initialize(attributes = {})
    @cve_presupuesto = attributes[:cve_presupuesto]
    @anio_presupuesto = attributes[:anio_presupuesto]
    @nombre_presupuesto = attributes[:nombre_presupuesto]
    @monto_presupuestado = attributes[:monto_presupuestado]
    @monto_erogado = attributes[:monto_erogado]
    @monto_por_erogar = attributes[:monto_por_erogar]
    @IdInterno = attributes[:IdInterno]
    @empresa_fk = attributes[:empresa_fk]
  end

  def self.all(page = 1, per_page = 10)
    response = get("/budgets/all")
    response.parsed_response  
  end

  def self.by_year(year)
    response = get("/budgets/by_year/#{year}")
    response.parsed_response  
  end

  def self.unique_years
    response = get("/budgets/unique_years")
    response.parsed_response  
  end

  def self.by_id(id)
    response = get("/budgets/by_id/#{id}")
    if response.success?
      budget_data = response.parsed_response

      Budget.new(
        IdInterno: budget_data["IdInterno"],
        cve_presupuesto: budget_data["cve_presupuesto"],
        anio_presupuesto: budget_data["anio_presupuesto"],
        nombre_presupuesto: budget_data["nombre_presupuesto"],
        monto_presupuestado: budget_data["monto_presupuestado"],
        monto_erogado: budget_data["monto_erogado"],
        monto_por_erogar: budget_data["monto_por_erogar"],
        empresa_fk: budget_data["empresaid"]
      )
    else
      nil
    end
  end

  def self.by_company_id(id)
    response = get("/budgets/by_company_id/#{id}")
    response.parsed_response
  end

  def self.create(data)
    response = HTTParty.post(
      "#{base_uri}/budgets/",
      body: data.to_json,
      headers: {
        'Content-Type' => 'application/json'
      }
    )
    response.code
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:demo]

  PAYMENT_METHODS = {
    1 => 'Cheque',
    2 => 'Transferencia',
    3 => 'Efectivo',
    4 => 'Tarjeta'
  }
  
  def index
    @years = Budget.unique_years
    @searched = false
    @companies = Company.all

    apply_search_filters if params[:search].present?

    latest_year = params[:year].presence || @years.max
    @budgets = Budget.by_year(latest_year)

    paginate_budgets

    @bank = Bank.new
    @budget = Budget.new
  end
          
  def new
    @companies = Supplier.all
    @bank = Bank.new
  end

  def create
    result = Budget.create(params)

    if result == 200
      flash[:success] = "El presupuesto se creó exitosamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al crear el presupuesto."
      render :new
    end
  end

  def details  
    @budgetline = Budgetline.new
    @check = Check.new
    @detail = Detail.new
    @payment_methods = PAYMENT_METHODS

    @budget = Budget.by_id(params[:id])
    @budgetlines = Budgetline.by_budget_id(params[:id])
    @banks = Bank.by_company_id(@budget.empresa_fk)

    @suppliers = Supplier.by_company_id(@budget.empresa_fk)
    @pending = Check.pending(params[:id])
    @amount_available = budget_amount_available

    @available_budgetlines = Budgetline.by_budget_id(params[:id])
    @pending_checks = Check.by_budget_id(params[:id])
  end

  def export
    @budget = Budget.by_id(params[:id])

    data = [
      ["Nombre", "Edad", "Ciudad"],
      ["Juan", 28, "Madrid"],
      ["Ana", 22, "Barcelona"],
      ["Luis", 31, "Valencia"]
    ]

    csv_data = CSV.generate(headers: true) do |csv|
      csv << ["Nombre", "Edad", "Ciudad"]
      data.each do |user|
        csv << user
      end
    end

    respond_to do |format|
      format.csv { send_data csv_data, filename: "presupuesto_#{@budget["IdInterno"]}_#{@budget["nombre_presupuesto"]}_#{Date.today}.csv" }
    end
  end

  def edit
    @companies = Company.all
    @budget = Budget.by_id(params[:id])
  end

  private

  def apply_search_filters
    search_term = params[:search].downcase
    @budgets.select! { |budget| budget["nombre_presupuesto"].downcase.include?(search_term) }
    @searched = true
  end

  def paginate_budgets
    @budgets = Kaminari.paginate_array(@budgets, total_count: @budgets.size).page(params[:page]).per(10)
  end

  def budget_amount_available
    amount = @budgetlines.map { |element| element["monto_presupuestado"] }.sum
    total = @budget.monto_presupuestado
    available = total -= amount
    available
  end
end

app/views/budgets/_create_budget.html.haml
.modal.fade#createBudgetModal{ tabindex: "-1", role: "dialog", aria: { labelledby: "exampleModalLabel", modal: true } }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title Crear Presupuesto
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" }, aria: { label: "Close" } }
          %span{ aria: { hidden: "true" } } &times;
      .modal-body
        = render 'budgets/create_budget_form', budget: @budget, companies: @companies
      .modal-footer
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" } } Cerrar

app/views/budgets/_create_budget_form.html.haml
= form_for budget, html: { class: "form" } do |f|
  .form-group.mb-3
    %strong= f.label :cve_presupuesto, "Clave", class: "form-label"
    = f.text_field :cve_presupuesto, class: "form-control"
    %p.danger-text#clave-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

  .form-group.mb-3
    %strong= f.label :anio_presupuesto, "Año", class: "form-label"
    = f.text_field :anio_presupuesto, class: "form-control"
    %p.danger-text#year-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

  .form-group.mb-3
    %strong= f.label :nombre_presupuesto, "Nombre", class: "form-label"
    = f.text_field :nombre_presupuesto, class: "form-control"
    %p.danger-text#name-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

  .form-group.mb-3
    %strong= f.label :monto_presupuestado, "Monto Presupuestado", class: "form-label"
    = f.text_field :monto_presupuestado, class: "form-control"
    %p.danger-text#amount-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

  .form-group.mb-3
    %strong= f.label :Empresa
    = f.select :empresa_fk, @companies.map{ |company| [company["Nombre"], company["IdInterno"]] }, {}, class: "form-control"

  .actions.d-flex.justify-content-end
    = f.submit 'Guardar', class: "btn btn-success", id: "saveButton", disabled: true

app/views/budgets/_create_budgetline.html.haml
.modal.fade#modalBudgetline{ tabindex: "-1", role: "dialog", aria: { labelledby: "exampleModalLabel", modal: true } }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title Crear Renglón
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" }, aria: { label: "Close" } }
          %span{ aria: { hidden: "true" } } &times;
      .modal-body
        = render 'budgets/create_budgetline_form', budgetline: @budgetline, budget_id: @budget.IdInterno
      .modal-footer
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" } } Cerrar

app/views/budgets/_create_budgetline_form.html.haml
= form_for budgetline, html: { class: "form" } do |f|
  = f.hidden_field :IdInternoPresupuesto, value: budget_id

  .form-group.mb-3
    = f.label :cve_renglon_presupuestal, "Clave", class: "form-label"
    = f.text_field :cve_renglon_presupuestal, class: "form-control"

  .form-group.mb-3
    = f.label :nombre_renglon_presupuestal, "Nombre", class: "form-label"
    = f.text_field :nombre_renglon_presupuestal, class: "form-control"

  .form-group.mb-3
    = f.label :monto_presupuestado, "Monto", class: "form-label"
    = f.text_field :monto_presupuestado, class: "form-control"

  .actions.d-flex.justify-content-end
    = f.submit 'Guardar', class: "btn btn-success", id: "saveButton", disabled: false

app/views/budgets/_create_check.html.haml
.modal.fade#modalCheck{ tabindex: "-1", role: "dialog", aria: { labelledby: "exampleModalLabel", modal: true } }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title Crear Cheque
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" }, aria: { label: "Close" } }
          %span{ aria: { hidden: "true" } } &times;
      .modal-body
        = render 'budgets/create_check_form', check: @check, budget_id: @budget.IdInterno, banks: @banks, suppliers: @suppliers
      .modal-footer
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" } } Cerrar

app/views/budgets/_create_check_form.html.haml
= form_for check, html: { class: "form" } do |f|
  = f.hidden_field :IdInternoPresupuesto, value: budget_id

  .form-group.mb-3
    %strong= f.label :fecha_emision_cheque, "Fecha y Hora"
    = f.date_field :fecha_emision_cheque, attribute: 'fecha_emision_cheque', class: 'form-control'

  .form-group.mb-3
    %strong= f.label :Banco
    = f.select :IdInternoBanco, @banks.map{ |bank| [bank.sucursal_banco, bank.IdInterno] }, {}, class: "form-control"

  .form-group.mb-3
    %strong= f.label :Proveedor
    = f.select :IdProveedorFK, @suppliers.map{ |supplier| [supplier["Nombre"], supplier["IdInterno"]] }, {}, class: "form-control"

  .form-group.mb-3
    %strong= f.label :Transacción
    = f.select :TransaccionType, @payment_methods.map{ |id, description| [description, id] }, {}, class: "form-control"

  .form-group.mb-3
    = f.label :num_cheque, "Número de cheque", class: "form-label"
    = f.text_field :num_cheque, class: "form-control"

  .form-group.mb-3
    = f.label :concepto_cheque, "Concepto", class: "form-label"
    = f.text_field :concepto_cheque, class: "form-control"

  .form-group.mb-3
    = f.label :Total, "Total", class: "form-label"
    = f.text_field :Total, class: "form-control"


  .actions.d-flex.justify-content-end
    = f.submit 'Guardar', class: "btn btn-success", id: "saveButton", disabled: false

app/views/budgets/_create_detail.html.haml
.modal.fade#modalDetail{ tabindex: "-1", role: "dialog", aria: { labelledby: "exampleModalLabel", modal: true } }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title Crear Movimiento de Transacción
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" }, aria: { label: "Close" } }
          %span{ aria: { hidden: "true" } } &times;
      .modal-body
        = render 'budgets/create_detail_form', detail: @detail, available_budgetlines: @available_budgetlines, pending_checks: @pending_checks
      .modal-footer
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" } } Cerrar

app/views/budgets/_pending.html.haml
.modal.fade#pendingModal{ tabindex: "-1", role: "dialog", aria: { labelledby: "exampleModalLabel", modal: true } }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title Transacciones pendientes de aprobación
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" }, aria: { label: "Close" } }
          %span{ aria: { hidden: "true" } } &times;
      .modal-body
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Concepto
              %th Total
              %th Acciones
            %tbody
              - @pending.each do |cheque|
                %tr
                  %td= cheque["concepto_cheque"]
                  %td{class: numeric_class(cheque["Total"])}
                    = number_to_currency(cheque["Total"])
                  %td.text-center
                    = link_to check_path(cheque["IdInterno"]), class: 'text-success icon-spacing' do
                      %i.fa.fa-eye

      .modal-footer
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" } } Cerrar

app/views/budgets/_tab_checks.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Fecha de emisión
      %th Concepto
      %th Total
      %th.text-center Status
      %th.text-center Acciones
      %th.text-center Autorizar
  %tbody
    - @checks.each do |cheque|
      %tr
        %td= formato_fecha_espanol(DateTime.parse(cheque["fecha_emision_cheque"]))
        %td= cheque["concepto_cheque"]
        %td{class: numeric_class(cheque["Total"])}
          = number_to_currency(cheque["Total"])
        %td.text-center{class: (cheque["autorizado"] == 1) ? 'text-success' : 'text-danger'}
          - if cheque["autorizado"] == 1
            Aprobado
          - else
            Pendiente
        %td.text-center
          %button.view-check-button.btn{type: "button", "data-budgetlines": @budgetlines.to_json, "data-details": @checkdetails.to_json, "data-checks": @checks.to_json, "data-element-id": "view_check_modal_#{cheque["IdInterno"]}"}
            %i.fa.fa-eye.text-success
          = link_to check_path(id: cheque["IdInterno"]), method: :delete, data: { confirm: "¿Estás seguro que deseas eliminar esta transacción?, se eliminaran todos los movimientos relacionados" } do
            %i.fa.fa-trash.text-danger
        %td.text-center
          - if cheque["autorizado"] == 1
            %button.view-check-button.btn.btn-danger{type: "button", "data-check-id": cheque["IdInterno"], onclick: "window.location.href='#{deauthorize_check_path(cheque["IdInterno"].to_s)}'"}
              Desaprobar
          - if cheque["autorizado"] == 0
            %button.view-check-button.btn.btn-success{type: "button", "data-check-id": cheque["IdInterno"], onclick: "window.location.href='#{authorize_check_path(cheque["IdInterno"].to_s)}'"}
              Aprobar

app/views/budgets/details.html.haml
= javascript_include_tag "application", defer: true

<br>
.text-center
  %h1{ style: "min-width: 200px;" }
    = link_to details_budget_path(id: @budget.IdInterno) do
      #{@budget.anio_presupuesto} - #{@budget.nombre_presupuesto}

- if flash[:success].present?
  .alert.alert-success= flash[:success]

- if flash[:error].present?
  .alert.alert-danger= flash[:error]

%br
%div{style: "display: flex; flex-direction: row; width: 100%; min-width: 00px;"}
  %div{style: "flex: 1; padding: 10px; max-width: 100%; margin-left: 10%; min-width: 100px;"}
    .container.p-3.bg-light{ style: "width: 70%; margin-left: 16%" }
      %label
        Agregar
        %button#budget_create_budgetline.btn.btn-primary{type: "button"} + Renglón
        %button#budget_create_check.btn.btn-primary{type: "button"} + Transacción
        %button#budget_create_detail.btn.btn-primary{type: "button"} + Movimiento
    %br
    .container.p-3.bg-light{ style: "width: 90%; margin-left: 16%;" }
      %label
        Visualizar
        %button#budget_view_budgetline.btn.btn-primary{type: "button"} Renglones
        = link_to 'Transacciones', details_check_path(@budget.IdInterno), class: 'btn btn-primary', id: 'checks_details'
        %button#budget_view_details.btn.btn-primary{type: "button"} Movimientos
        = link_to "Exportar", export_budget_path(format: :csv), class: "btn btn-success", id: "loadButton", method: :get
  
  %div{style: "flex: 1; padding: 10px; max-width: 50%; margin-right: 200px"}
    - presupuestado = @budget.monto_presupuestado.to_f
    - erogado = @budget.monto_erogado.to_f
    - por_erogar = @budget.monto_por_erogar.to_f
    - total = presupuestado
    - total = 1 if total.zero?

    - porcentaje_erogado = ((erogado / total) * 100).round
    - porcentaje_por_erogar = ((por_erogar / total) * 100).round
    = pie_chart [["Por erogar", porcentaje_por_erogar], ["Erogado", porcentaje_erogado]], colors: ["#59b41b", "#b8250e"]
= render partial: 'create_budgetline'
= render partial: 'create_check'
= render partial: 'create_detail'
= render partial: 'pending'
= render partial: 'view_checks'
= render partial: 'view_check_detail'

%br
.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Clave
                %th Año
                %th Nombre
                %th Presupuestado
                %th Erogado
                %th Por Erogar
                %th Progreso
            %tbody
              %tr
                %td= @budget.cve_presupuesto
                %td= @budget.anio_presupuesto
                %td= @budget.nombre_presupuesto
                %td{class: numeric_class(@budget.monto_presupuestado)}
                  = number_to_currency(@budget.monto_presupuestado)
                %td{class: numeric_class(@budget.monto_erogado)}
                  = number_to_currency(@budget.monto_erogado)
                %td{class: numeric_class(@budget.monto_por_erogar)}
                  = number_to_currency(@budget.monto_por_erogar)
                %td
                  .progress
                    - monto_presupuestado_budget = @budget.monto_presupuestado
                    - monto_erogado_budget = @budget.monto_erogado

                    - if monto_presupuestado_budget.present? && monto_presupuestado_budget.to_f != 0
                      - progress_value = (monto_erogado_budget.to_f / monto_presupuestado_budget.to_f * 100).to_i
                      .progress-bar{role: "progressbar", style: "width: #{progress_value}%", "aria-valuenow": progress_value, "aria-valuemin": 0, "aria-valuemax": 100}
                    - else
                      .progress-bar{role: "progressbar", style: "width: 0%", "aria-valuenow": 0, "aria-valuemin": 0, "aria-valuemax": 100}

.container.mx-auto.my-5.p-3.bg-light
  %table.table.text-center
    %thead
      %tr
        %th Total de Renglónes
        %th Transacciones Pendientes
        %th Monto sin asignar
    %tbody
      %tr
        %td= @budgetlines.size
        %td= link_to "#{@pending.size} transacciones", "#", id: "link_to_pendingModal"
        %td{class: numeric_class(@amount_available)}
          = number_to_currency(@amount_available)

.container
  .row
    .col-xs-12
      .custom-table-container

        .text-center
          %h1#renglones Renglónes

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Clave
                %th Nombre
                %th Presupuestado
                %th Erogado
                %th Por Erogar
                %th Progreso
                %th Acciones
            %tbody
              - @budgetlines.each do |budgetline|
                %tr
                  %td= budgetline["cve_renglon_presupuestal"]
                  %td= budgetline["nombre_renglon_presupuestal"]
                  %td{class: numeric_class(budgetline["monto_presupuestado"])}
                    = number_to_currency(budgetline["monto_presupuestado"])
                  %td{class: numeric_class(budgetline["monto_erogado"])}
                    = number_to_currency(budgetline["monto_erogado"])
                  %td{class: numeric_class(budgetline["monto_por_erogar"])}
                    = number_to_currency(budgetline["monto_por_erogar"])
                  %td
                    .progress
                      - monto_presupuestado_budgetline = budgetline["monto_presupuestado"]
                      - monto_erogado_budgetline = budgetline["monto_erogado"]

                      - if monto_presupuestado_budgetline.present? && monto_presupuestado_budgetline.to_f != 0
                        - progress_value = (monto_erogado_budgetline.to_f / monto_presupuestado_budgetline.to_f * 100).to_i
                        .progress-bar{role: "progressbar", style: "width: #{progress_value}%", "aria-valuenow": progress_value, "aria-valuemin": 0, "aria-valuemax": 100}
                      - else
                        .progress-bar{role: "progressbar", style: "width: 0%", "aria-valuenow": 0, "aria-valuemin": 0, "aria-valuemax": 100}
                  %td.text-center
                    = link_to budgetline_path(id: budgetline["IdInterno"]) do
                      %i.fa.fa-eye.text-success.text-decoration-none
                    %button.download-check-button.btn{type: "button", "data-budgetlines": @budgetlines.to_json, "data-details": @checkdetails.to_json, "data-checks": @checks.to_json, "data-element-id": "view_check_modal_#{budgetline["IdInterno"]}"}
                      %i.fa.fa-download.text-success
                    = link_to budgetline_path(id: budgetline["IdInterno"]), method: :delete, data: { confirm: "¿Estás seguro que deseas eliminar esta renglón?, se eliminaran todos los movimientos y cheques relacionados" } do
                      %i.fa.fa-trash.text-danger


<br>
<br>
<br>

app/views/budgets/edit.html.haml
.text-center.mt-5.mb-5
  %h1 Editar Presupuesto

.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3.d-flex.justify-content-center
            = form_for @budget, url: budget_path(@budget.IdInterno), method: :patch, html: { class: "form", style: "max-width: 600px; width: 100%; margin: 0 auto;" } do |f|
              = f.hidden_field :IdInterno, value: @budget.IdInterno

              .form-group.mb-3
                %strong= f.label :cve_presupuesto, "Clave", class: "form-label"
                = f.text_field :cve_presupuesto, class: "form-control"
                %p.danger-text#clave-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :anio_presupuesto, "Año", class: "form-label"
                = f.text_field :anio_presupuesto, class: "form-control"
                %p.danger-text#year-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :nombre_presupuesto, "Nombre", class: "form-label"
                = f.text_field :nombre_presupuesto, class: "form-control"
                %p.danger-text#name-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :monto_presupuestado, "Monto Presupuestado", class: "form-label"
                %div{class: "input-group"}
                  %span.input-group-text $
                  = f.text_field :monto_presupuestado, class: "form-control"
                  %p.danger-text#amount-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :monto_erogado, "Monto Erogado", class: "form-label"
                %div{class: "input-group"}
                  %span.input-group-text $
                  = f.text_field :monto_erogado, class: "form-control", readonly: true
                %p.danger-text#amount-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :monto_por_erogar, "Monto Por Erogar", class: "form-label"
                %div{class: "input-group"}
                  %span.input-group-text $
                  = f.text_field :monto_por_erogar, class: "form-control"
                  %p.danger-text#amount-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :Empresa
                = f.select :empresa_fk, @companies.map{ |company| [company["Nombre"], company["IdInterno"]] }, {}, class: "form-control"

              .actions.d-flex.justify-content-end
                = f.submit 'Guardar', class: "btn btn-success", id: "saveButton", disabled: true

app/views/budgets/index.html.haml
.text-center
  %h1 Presupuestos

- if flash[:success].present?
  .alert.alert-success= flash[:success]

- if flash[:error].present?
  .alert.alert-danger= flash[:error]

= render partial: 'create_budget'

.container.mx-auto.my-5.p-3.bg-light
  %button#createBudget.btn.btn-primary{type: "button"} Crear

.container.mx-auto.my-5.p-3.bg-light
  %label
    Selecciona un año:
    
  .btn-group
    %form{method: :get, onchange: 'this.submit();'}
      %select.form-select{name: 'year', class: 'btn btn-success dropdown-toggle'}
        - @years.each do |opcion|
          %option{value: opcion, selected: (opcion.to_s == params[:year].to_s)}= opcion

.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3
            %form{action: "/budgets", method: "get"}
              .input-group.mb-3
                %input#filtroInput.form-control{type: "text", placeholder: "Buscar por nombre...", name: "search", aria_label: "Buscar"}
                %button.btn.btn-outline-secondary{type: "submit"} Buscar
              - if @searched
                %a.btn.btn-danger{href: "/budgets"} Reiniciar Búsqueda

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Clave
                %th Año
                %th Nombre
                %th Monto Presupuestado
                %th Erogado
                %th Por Erogar
                %th Acciones

            %tbody
              - @budgets.each do |budget|
                %tr
                  %td= budget["cve_presupuesto"]
                  %td= budget["anio_presupuesto"]
                  %td= budget["nombre_presupuesto"]
                  %td{class: numeric_class(budget["monto_presupuestado"])}
                    = number_to_currency(budget["monto_presupuestado"])
                  %td{class: numeric_class(budget["monto_erogado"])}
                    = number_to_currency(budget["monto_erogado"])
                  %td{class: numeric_class(budget["monto_por_erogar"])}
                    = number_to_currency(budget["monto_por_erogar"])
                  %td 
                    = link_to details_budget_path(budget["IdInterno"]), class: 'text-success me-1 text-decoration-none' do
                      %i.fa.fa-eye
                    - if can_edit?(current_profile.rol)
                      = link_to edit_budget_path(budget["IdInterno"]), class: 'text-warning text-decoration-none' do
                        %i.fa.fa-pencil
                    = link_to details_budget_path(budget["IdInterno"]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger icon-spacing' do
                      %i.fa.fa-trash

        .pagination-container
          = paginate @budgets