config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  match '/users',   to: 'users#index',   via: 'get'
  resources :banks
  resources :companies
  resources :suppliers
  resources :budgetlines
  resources :backups
  resources :home
  resources :bulk_upload
  resources :profiles
  resources :users do
    member do
      get 'details'
      get :edit_password
      put :update_password  
      delete :destroy
    end
  end
  get 'unauthorized', to: 'errors#unauthorized', as: :unauthorized

  resources :budgets do
    member do
      get 'details'
    end
  end
  resources :checks do
    member do
      get 'details'
    end
  end
  resources :details
  resources :searchs
  get '/checks/authorize/:id', to: 'checks#authorize', as: 'authorize_check'
  get '/checks/deauthorize/:id', to: 'checks#deauthorize', as: 'deauthorize_check'
  get 'budgets/:id/export', to: 'budgets#export', as: 'export_budget'
  get '/', to: redirect('home/index')
  resource :example, constraints: -> { Rails.env.development? }
  post 'bulkupload', to: 'bulk_upload#create', as: :bulkupload
  get 'bulkupload/download_layout', to: 'bulk_upload#download_layout', as: :download_layout
end

app/models/company.rb
class Company
  include HTTParty
  base_uri Rails.application.config.base_api
  include ActiveModel::Model
  attr_accessor :IdInterno, :name, :address, :phone_number, :rfc

  def initialize(attributes = {})
    @IdInterno = attributes[:IdInterno]
    @name = attributes[:name]
    @address = attributes[:address]
    @phone_number = attributes[:phone_number]
    @rfc = attributes[:rfc]
  end

  def self.all
    response = get('/companies/all')
    response.parsed_response
  end

  def self.by_id(id)
    response = get("/companies/by_id/#{id}")

    if response.success?
      company_data = response.parsed_response
      Company.new(
        IdInterno: company_data["IdInterno"],
        name: company_data["Nombre"],
        address: company_data["Domicilio"],
        phone_number: company_data["Telefono"],
        rfc: company_data["RFC"]
      )
    else
      nil
    end
  end

  def self.create(data)
    response = HTTParty.post(
      "#{base_uri}/company/",
      body: data.to_json,
      headers: {
        'Content-Type' => 'application/json'
      }
    )

    response.parsed_response
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    
  def index
    @company = Company.new
    @companies = Company.all
    @searched = false

    if params[:search].present?
      search_term = params[:search].downcase
      @companies = @companies.select { |bank| bank["Nombre"].downcase.include?(search_term) }
      @searched = true
    end
    @companies = Kaminari.paginate_array(@companies, total_count: @companies.size).page(params[:page]).per(10)
    @companie = Bank.new
  end
      
  def new
    @companies = Company.all
    @bank = Bank.new
  end

  def create
    result = Bank.create(params)
    if result == 200
      flash[:success] = "La empresa se creó exitosamente."
      redirect_to index
    else
      flash[:error] = "Hubo un error al crear la empresa."
      render :new
    end
  end

  def edit
    @company = Company.by_id(params[:id])
  end
  
  private

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_create.html.haml
.modal.fade#myModal{ tabindex: "-1", role: "dialog", aria: { labelledby: "exampleModalLabel", modal: true } }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title Crear
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" }, aria: { label: "Close" } }
          %span{ aria: { hidden: "true" } } &times;
      .modal-body
        = render 'companies/form', company: @company
      .modal-footer
        %button.btn.btn-secondary{ type: "button", data: { dismiss: "modal" } } Cerrar

app/views/companies/_form.html.haml
= form_for company, html: { class: "form" } do |f|
  .form-group.mb-3
    %strong= f.label :Nombre
    = f.text_field :name, class: "form-control"

  .form-group.mb-3
    %strong= f.label :Dirección
    = f.text_field :address, class: "form-control"

  .form-group.mb-3
    %strong= f.label :Telefono
    = f.text_field :phone_number, class: "form-control"
    %p.danger-text#telefono-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

  .form-group.mb-3
    %strong= f.label :rfc, "RFC"
    = f.text_field :rfc, class: "form-control"

  .actions.d-flex.justify-content-end
    = f.submit 'Guardar', class: "btn btn-success", id: "saveButton", disabled: false

app/views/companies/edit.html.haml
.text-center.mt-5.mb-5
  %h1 Editar Empresa

.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3.d-flex.justify-content-center
            = form_for @company, url: companies_path(@company.IdInterno), method: :patch, html: { class: "form", style: "max-width: 600px; width: 100%; margin: 0 auto;" } do |f|
              = f.hidden_field :IdInterno, value: @company.IdInterno

              .form-group.mb-3
                %strong= f.label :name, "Nombre"
                = f.text_field :name, class: "form-control"
                %p.danger-text#clave-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :address, "Domicilio"
                = f.text_field :address, class: "form-control"
                %p.danger-text#clave-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :phone_number, "Telefono"
                = f.text_field :phone_number, class: "form-control"
                %p.danger-text#clave-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .form-group.mb-3
                %strong= f.label :rfc, "RFC"
                = f.text_field :rfc, class: "form-control"
                %p.danger-text#telefono-error{style: 'display: none;'} La data es incorrecta. Por favor, verifica los datos.

              .actions.d-flex.justify-content-end
                = f.submit 'Guardar', class: "btn btn-success", id: "saveButton", disabled: true

app/views/companies/index.html.haml
.text-center
  %h1 Empresas


= render partial: 'create'

- if flash[:success].present?
  .alert.alert-success= flash[:success]

- if flash[:error].present?
  .alert.alert-danger= flash[:error]

.container.mx-auto.my-5.p-3.bg-light
  %button#crearButton.btn.btn-primary{type: "button"} Crear

.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3
            %form{action: "/companies", method: "get"}
              .input-group.mb-3
                %input#filtroInput.form-control{type: "text", placeholder: "Buscar por nombre...", name: "search", aria_label: "Buscar"}
                %button.btn.btn-outline-secondary{type: "submit"} Buscar
              - if @searched
                %a.btn.btn-danger{href: "/companies"} Reiniciar Búsqueda

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Nombre
                %th Domicilio
                %th Telefono
                %th RFC
                %th Acciones
            %tbody
              - @companies.each do |company|
                %tr
                  %td= company["Nombre"]
                  %td= company["Domicilio"]
                  %td= company["Telefono"]
                  %td= company["RFC"]
                  %td.text-center
                    - if can_edit?(current_profile.rol)
                      = link_to edit_company_path(company["IdInterno"]), class: 'text-warning text-decoration-none' do
                        %i.fa.fa-pencil
                    = content_tag :span, ' ', class: 'mx-2'
                    = link_to budgetline_path(id: 1) do
                      %i.fa.fa-trash.text-danger.text-decoration-none
        .pagination-container
          = paginate @companies