config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  match '/users',   to: 'users#index',   via: 'get'
  resources :banks
  resources :companies
  resources :suppliers
  resources :budgetlines
  resources :backups
  resources :home
  resources :bulk_upload
  resources :profiles
  resources :users do
    member do
      get 'details'
      get :edit_password
      put :update_password  
      delete :destroy
    end
  end
  get 'unauthorized', to: 'errors#unauthorized', as: :unauthorized

  resources :budgets do
    member do
      get 'details'
    end
  end
  resources :checks do
    member do
      get 'details'
    end
  end
  resources :details
  resources :searchs
  get '/checks/authorize/:id', to: 'checks#authorize', as: 'authorize_check'
  get '/checks/deauthorize/:id', to: 'checks#deauthorize', as: 'deauthorize_check'
  get 'budgets/:id/export', to: 'budgets#export', as: 'export_budget'
  get '/', to: redirect('home/index')
  resource :example, constraints: -> { Rails.env.development? }
  post 'bulkupload', to: 'bulk_upload#create', as: :bulkupload
  get 'bulkupload/download_layout', to: 'bulk_upload#download_layout', as: :download_layout
end

app/models/budgetline.rb
class Budgetline
    include HTTParty
    base_uri Rails.application.config.base_api
    include ActiveModel::Model
    attr_accessor :cve_renglon_presupuestal, :nombre_renglon_presupuestal, :monto_presupuestado, :monto_erogado, :monto_por_erogar
  
    def initialize(attributes = {})
      @cve_renglon_presupuestal = attributes[:cve_renglon_presupuestal]
      @nombre_renglon_presupuestal = attributes[:nombre_renglon_presupuestal]
      @monto_presupuestado = attributes[:monto_presupuestado]
      @monto_erogado = attributes[:monto_erogado]
      @monto_por_erogar = attributes[:monto_por_erogar]  
    end
  
    def self.all(page = 1, per_page = 10)
      @request_ = RequestHandler.new('budgetlines')
      @request_.all
    end
  
    def self.unique_years()
      response = get("/budgetlines/unique_years")
      response.parsed_response  
    end

    def self.by_id(id)
      response = get("/budgetlines/by_id/#{id}")
      response.parsed_response
    end
  
    def self.by_budget_id(id)
      response = get("/budgetlines/by_budget_id/#{id}")
      response.parsed_response
    end

    def self.by_name(name)
      response = get("/budgetlines/by_name/#{name}")
      response.parsed_response
    end

    def self.delete(id)
      response = get("/budgetlines/delete/#{id["id"]}")
      response.code
    end
  
    def self.create(data)
      response = HTTParty.post(
        "#{base_uri}/budgetlines/",
        body: data.to_json,
        headers: {
          'Content-Type' => 'application/json'
        }
      )
      response.code
    end  
  end
  

app/controllers/budgetlines_controller.rb
class BudgetlinesController < ApplicationController 
  def index
    @budgets = Budget.all
    @years = Budget.unique_years
    @searched = false
    
    apply_search_filters if params[:search].present?
    
    latest_year = params[:year].presence || @years.max
    filter_by_year(latest_year)
    
    paginate_budgets
    
    @bank = Bank.new
  end

  def show
    @budgetline = Budgetline.by_id(params[:id])
    @budget = Budget.by_id(@budgetline['IdInternoPresupuesto'])
    @checkdetails = Detail.by_budgetline_id(@budgetline["IdInterno"])
    @banks = Bank.all

    detail_ids = @checkdetails.map(&:IdInternoCheque).uniq
    checks = detail_ids.map do |detail_id|
      Check.by_id(detail_id)
    end

    @checks = checks.sort_by do |cheque|
      fecha = cheque.fecha_emision_cheque
      fecha.nil? ? DateTime.new(0) : DateTime.parse(fecha)
    end
    cheques_hash = @checks.each_with_object({}) do |cheque, hash|
    hash[cheque.IdInterno] = cheque
    end
    @merged_details = @checkdetails.map do |detail|
      cheque = cheques_hash[detail.IdInternoCheque]
    
      detail_hash = {
        importe_renglon: detail.instance_variable_get(:@importe_renglon),
        id_interno: detail.instance_variable_get(:@IdInterno),
        id_interno_cheque: detail.instance_variable_get(:@IdInternoCheque),
        id_interno_renglon: detail.instance_variable_get(:@IdInternoRenglon),
        description: detail.instance_variable_get(:@description)
      }
    
      cheque_hash = cheque ? {
        fecha_emision_cheque: cheque.instance_variable_get(:@fecha_emision_cheque),
        concepto_cheque: cheque.instance_variable_get(:@concepto_cheque),
        estatus_pago_cheque: cheque.instance_variable_get(:@estatus_pago_cheque),
        autorizado: cheque.instance_variable_get(:@autorizado),
        id_interno: cheque.instance_variable_get(:@IdInterno),
        id_interno_banco: cheque.instance_variable_get(:@IdInternoBanco),
        id_interno_presupuesto: cheque.instance_variable_get(:@IdInternoPresupuesto),
        total: cheque.instance_variable_get(:@Total),
        num_cheque: cheque.instance_variable_get(:@num_cheque),
        transaccion_type: cheque.instance_variable_get(:@TransaccionType),
        id_proveedor_fk: cheque.instance_variable_get(:@IdProveedorFK)
      } : {}
    
      detail_hash.merge(cheque_hash)
    end
  end
          
  def new
    @companies = Supplier.all
    @bank = Bank.new
  end
  
  def create
    result = Budgetline.create(params)
    if result == 200
      flash[:success] = "El renglón se creó exitosamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al crear el renglón."
      render :new
    end
  end

  def destroy
    result = Budgetline.delete(params)
    if result == 200
      flash[:success] = "El renglón se elimino exitosamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al eliminar el renglón."
      redirect_to request.referrer || root_path
    end
  end

  def details     
    @budget = Budget.by_id(params[:id])
    @budgetlines = Budgetline.by_budget_id(params[:id])
    @budgetline = Budgetline.new
  end
end

app/views/budgetlines/show.html.haml
= javascript_include_tag "application", defer: true

<br>
.text-center
  %h1
    = link_to details_budget_path(id: @budget.IdInterno) do
      #{@budget.anio_presupuesto} - #{@budget.nombre_presupuesto}
  %br
  %h1
    = link_to budgetline_path(id: @budgetline["IdInterno"]) do
      #{@budgetline["cve_renglon_presupuestal"]} - #{@budgetline["nombre_renglon_presupuestal"]}

.container.mt-3
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Clave
                %th Nombre
                %th Presupuestado
                %th Erogado
                %th Por Erogar
                %th Progreso
            %tbody
              %tr
                %td= @budgetline["cve_renglon_presupuestal"]
                %td= @budgetline["nombre_renglon_presupuestal"]
                %td{class: numeric_class(@budgetline["monto_presupuestado"])}
                  = number_to_currency(@budgetline["monto_presupuestado"])
                %td{class: numeric_class(@budgetline["monto_erogado"])}
                  = number_to_currency(@budgetline["monto_erogado"])
                %td{class: numeric_class(@budgetline["monto_por_erogar"])}
                  = number_to_currency(@budgetline["monto_por_erogar"])
                %td
                  .progress
                    - monto_presupuestado_budget = @budgetline["monto_presupuestado"]
                    - monto_erogado_budget = @budgetline["monto_erogado"]
                    - if monto_presupuestado_budget.present? && monto_presupuestado_budget.to_f != 0
                      - progress_value = (monto_erogado_budget.to_f / monto_presupuestado_budget.to_f * 100).to_i
                      .progress-bar{role: "progressbar", style: "width: #{progress_value}%", "aria-valuenow": progress_value, "aria-valuemin": 0, "aria-valuemax": 100}
                    - else
                      .progress-bar{role: "progressbar", style: "width: 0%", "aria-valuenow": 0, "aria-valuemin": 0, "aria-valuemax": 100}

<br>
<br>
<br>
.text-center
  %h1#cheques_y_movimientos Movimientos

.container.mt-3
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3
            %table.table.table-striped.table-bordered
              %thead
                %tr
                  %th Banco
                  %th Transacción
                  %th Descripción
                  %th Total
                  %th Status
                  %th Acciones
              %tbody
                - @merged_details.each do |detail|
                  %tr
                    %td= link_to (@banks.find { |bank| bank["IdInterno"] == detail[:id_interno_banco] }["nombre_banco"] rescue "Banco no encontrado"), bank_path(detail[:id_interno_banco])
                    %td= link_to "#{detail[:num_cheque]} - #{detail[:concepto_cheque]}", check_path(detail[:id_interno_cheque])
                    %td= detail[:description]
                    %td{class: numeric_class(detail[:importe_renglon])}
                      = number_to_currency(detail[:importe_renglon])
                    %td.text-center
                      - if detail[:autorizado] == 1
                        %i.fa.fa-check(style="color: green")
                      - else
                        %i.fa.fa-times(style="color: red")
                    %td.text-center
                      = link_to checks_path(id: detail["IdInterno"]) do
                        %i.fa.fa-eye.text-success.text-decoration-none