config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  match '/users',   to: 'users#index',   via: 'get'
  resources :banks
  resources :companies
  resources :suppliers
  resources :budgetlines
  resources :backups
  resources :home
  resources :bulk_upload
  resources :profiles
  resources :users do
    member do
      get 'details'
      get :edit_password
      put :update_password  
      delete :destroy
    end
  end
  get 'unauthorized', to: 'errors#unauthorized', as: :unauthorized

  resources :budgets do
    member do
      get 'details'
    end
  end
  resources :checks do
    member do
      get 'details'
    end
  end
  resources :details
  resources :searchs
  get '/checks/authorize/:id', to: 'checks#authorize', as: 'authorize_check'
  get '/checks/deauthorize/:id', to: 'checks#deauthorize', as: 'deauthorize_check'
  get 'budgets/:id/export', to: 'budgets#export', as: 'export_budget'
  get '/', to: redirect('home/index')
  resource :example, constraints: -> { Rails.env.development? }
  post 'bulkupload', to: 'bulk_upload#create', as: :bulkupload
  get 'bulkupload/download_layout', to: 'bulk_upload#download_layout', as: :download_layout
end

app/models/check.rb
class Check
  include HTTParty
  base_uri Rails.application.config.base_api
  include ActiveModel::Model
  attr_accessor :fecha_emision_cheque, :concepto_cheque, :estatus_pago_cheque, :autorizado, :IdInterno, :IdInternoBanco, 
                :num_cheque, :IdInternoPresupuesto, :Total, :TransaccionType, :IdProveedorFK

  def initialize(attributes = {})
    @fecha_emision_cheque = attributes[:fecha_emision_cheque]
    @concepto_cheque = attributes[:concepto_cheque]
    @estatus_pago_cheque = attributes[:estatus_pago_cheque]
    @autorizado = attributes[:autorizado]
    @IdInterno = attributes[:IdInterno]
    @IdInternoBanco = attributes[:IdInternoBanco]
    @IdInternoPresupuesto = attributes[:IdInternoPresupuesto]
    @Total = attributes[:Total]
    @num_cheque = attributes[:num_cheque]
    @TransaccionType = attributes[:TransaccionType]
    @IdProveedorFK = attributes[:IdProveedorFK]
  end

  def self.all(page = 1, per_page = 10)
    @request_ = RequestHandler.new('budgets')
    @request_.all
  end

  def self.unique_years
    response = get("/budgets/unique_years")
    response.parsed_response
  end

  def self.by_id(id)
    response = get("/checks/by_id/#{id}")
    if response.success?
      checks_data = response.parsed_response

      Check.new(
        fecha_emision_cheque: checks_data["fecha_emision_cheque"],
        concepto_cheque: checks_data["concepto_cheque"],
        estatus_pago_cheque: checks_data["estatus_pago_cheque"],
        autorizado: checks_data["autorizado"],
        IdInterno: checks_data["IdInterno"],
        IdInternoBanco: checks_data["IdInternoBanco"],
        IdInternoPresupuesto: checks_data["IdInternoPresupuesto"],
        Total: checks_data["Total"],
        TransaccionType: checks_data["TransaccionType"],
        num_cheque: checks_data["num_cheque"],
        IdProveedorFK: checks_data["IdProveedorFK"]
      )
    else
      nil
    end
  end

  def self.by_budget_id(id)
    response = get("/checks/by_budget_id/#{id}")

    if response.success?
      check_data_array = response.parsed_response
  
      check_data_array.map do |check_data|
        Check.new(
          fecha_emision_cheque: check_data["fecha_emision_cheque"],
          concepto_cheque: check_data["concepto_cheque"],
          estatus_pago_cheque: check_data["estatus_pago_cheque"],
          autorizado: check_data["autorizado"],
          IdInterno: check_data["IdInterno"],
          IdInternoBanco: check_data["IdInternoBanco"],
          IdInternoPresupuesto: check_data["IdInternoPresupuesto"],
          Total: check_data["Total"],
          TransaccionType: check_data["TransaccionType"],
          num_cheque: check_data["num_cheque"],
          IdProveedorFK: check_data["IdProveedorFK"]
          )
      end
    else
      []
    end
  end

  def self.pending(id)
    response = get("/checks/pending/#{id}")
    response.parsed_response
  end

  def self.authorize(id)
    response = get("/checks/authorize/#{id["id"]}")
    response.code
  end

  def self.deauthorize(id)
    response = get("/checks/deauthorize/#{id["id"]}")
    response.code
  end

  def self.delete(id)
    response = get("/checks/delete/#{id["id"]}")
    response.code
  end

  def self.create(data)
    response = HTTParty.post(
      "#{base_uri}/checks/",
      body: data.to_json,
      headers: {
        'Content-Type' => 'application/json'
      }
    )
    response.code
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController 
  PAYMENT_METHODS = {
    1 => 'Cheque',
    2 => 'Transferencia',
    3 => 'Efectivo',
    4 => 'Tarjeta'
  }

  def details
    @payment_methods = PAYMENT_METHODS
    @budget = Budget.by_id(params[:id])
    @checks = Check.by_budget_id(@budget.IdInterno)
    if params[:sort].present? && params[:direction].present?
      @checks = @checks.sort_by do |check|
        value = check.send(params[:sort])
        value.nil? ? '' : value
      end
    
      @checks.reverse! if params[:direction] == 'desc'
    end
  end

  def show
    @payment_methods = PAYMENT_METHODS
    @check = Check.by_id(params[:id])
    @budget = Budget.by_id(@check.IdInternoPresupuesto)
    @supplier = Supplier.by_id(@check.IdProveedorFK)
    @details = Detail.by_check_id(@check.IdInterno)
    @budgetlines = @details.map do |detail|
      Budgetline.by_id(detail.IdInternoRenglon)
    end
  end

  def authorize
    result = Check.authorize(params)

    if result == 200
      flash[:success] = "El cheque aprobó correctamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al aprobar el cheque."
      render :new
    end
  end

  def deauthorize
    result = Check.deauthorize(params)

    if result == 200
      flash[:success] = "El cheque desaprobó correctamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al desaprobar el cheque."
      render :new
    end
  end

  def create
    result = Check.create(params)

    if result == 200
      flash[:success] = "El cheque se creó exitosamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al crear el cheque."
      render :new
    end
  end

  def destroy
    result = Check.delete(params)

    if result == 200
      flash[:success] = "La transacción se eliminó exitosamente."
      redirect_to request.referrer || root_path
    else
      flash[:error] = "Hubo un error al eliminar la transacción."
      redirect_to request.referrer || root_path
    end
  end
end

app/views/checks/details.html.haml
%br
.text-center
  %h1
    = link_to details_budget_path(id: @budget.IdInterno) do
      #{@budget.anio_presupuesto} - #{@budget.nombre_presupuesto}

%br
.text-center
  %h1 Transacciones

%br
.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3
          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th
                  = link_to 'Clave', details_check_path(sort: 'num_cheque', direction: params[:direction] == 'asc' ? 'desc' : 'asc')
                %th
                  = link_to 'Nombre', details_check_path(sort: 'concepto_cheque', direction: params[:direction] == 'asc' ? 'desc' : 'asc')
                %th
                  = link_to 'Status', details_check_path(sort: 'estatus_pago_cheque', direction: params[:direction] == 'asc' ? 'desc' : 'asc')
                %th
                  = link_to 'Tipo de Transacción', details_check_path(sort: 'estatus_pago_cheque', direction: params[:direction] == 'asc' ? 'desc' : 'asc')
                %th
                  = link_to 'Total', details_check_path(sort: 'Total', direction: params[:direction] == 'asc' ? 'desc' : 'asc')
                %th
                  = link_to 'Autorizado', details_check_path(sort: 'autorizado', direction: params[:direction] == 'asc' ? 'desc' : 'asc')
                %th Acciones
            %tbody
              - @checks.each do |check|
                %tr
                  %td= check.num_cheque
                  %td= check.concepto_cheque
                  %td= check.estatus_pago_cheque
                  %td= @payment_methods[check.TransaccionType]
                  %td{class: numeric_class(check.Total)}
                    = number_to_currency(check.Total)
                  %td.text-center
                    - if check.autorizado == 1
                      %i.fa.fa-check(style="color: green")
                    - else
                      %i.fa.fa-times(style="color: red")
                  %td
                    = link_to check_path(check.IdInterno), class: 'text-success icon-spacing' do
                      %i.fa.fa-eye

app/views/checks/show.html.haml
= javascript_include_tag "application", defer: true

<br>
.text-center
  %h1
    = link_to details_budget_path(id: @budget.IdInterno) do
      #{@budget.anio_presupuesto} - #{@budget.nombre_presupuesto}
  %br
  %h1

.container.mx-auto.my-5.p-3.bg-light
  - if can_create?(current_profile.rol)
    %button#crearButton.btn.btn-primary{type: "button"} Editar
  - if can_approve?(current_profile.rol)
    - if @check.autorizado == 0
      %button.view-check-button.btn.btn-success{type: "button", "data-check-id": @check.IdInterno, onclick: "window.location.href='#{authorize_check_path(@check.IdInterno.to_s)}'"}
        Aprobar
    - else
      %button.view-check-button.btn.btn-danger{type: "button", "data-check-id": @check.IdInterno, onclick: "window.location.href='#{deauthorize_check_path(@check.IdInterno.to_s)}'"}
        Desaprobar


.text-center
  %h1 Transacción

.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Numero
                %th Concepto
                %th Status
                %th Autorizado
            %tbody
              %tr
                %td= @check.num_cheque
                %td= @check.concepto_cheque
                %td.text-center= @check.estatus_pago_cheque
                %td.text-center
                  - if @check.autorizado == 1
                    %i.fa.fa-check(style="color: green")
                  - else
                    %i.fa.fa-times(style="color: red")

.container
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3

          %table.table.table-striped.table-bordered
            %thead.thead-dark
              %tr
                %th Fecha Emisión
                %th Tipo de Transacción
                %th Total
                %th Proveedor
            %tbody
              %tr
                %td= @check.fecha_emision_cheque.present? ? Time.parse(@check.fecha_emision_cheque).strftime("%d/%m/%Y") : "N/A"
                %td= @payment_methods[@check.TransaccionType]
                %td{class: numeric_class(@check.Total)}
                  = number_to_currency(@check.Total)
                %td
                  = link_to @supplier.name, supplier_path(@supplier.IdInterno)
%br
.text-center
  %h1 Movimientos

.container.mt-3
  .row
    .col-xs-12
      .custom-table-container
        .tabla-container
          %div.input-group.mb-3
            %table.table.table-striped.table-bordered
              %thead
                %tr
                  %th Renglón
                  %th Importe
                  %th Descripción
                  %th Acciones
              %tbody
                - @details.each do |detail|
                  %tr
                    %td
                      - budget_line = @budgetlines.find { |line| line["IdInterno"] == detail.IdInternoRenglon }
                      - if budget_line
                        = link_to "#{budget_line['cve_renglon_presupuestal']} - #{budget_line['nombre_renglon_presupuestal']}", budgetline_path(budget_line["IdInterno"])
                    %td{class: numeric_class(detail.importe_renglon)}
                      = number_to_currency(detail.importe_renglon)
                    %td= detail.description
                    %td
                      =link_to edit_bank_path(budget_line["IdInterno"]), class: 'text-warning text-decoration-none' do
                        %i.fa.fa-pencil